export enum GameErrorCode {
  NO_ATTACK_AVAILABLE_BY_ENERGY = "NO_ATTACK_AVAILABLE_BY_ENERGY",
  NO_ATTACK_AVAILABLE_BY_COOLDOWN = "NO_ATTACK_AVAILABLE_BY_COOLDOWN",
  SKIP_TURN = "SKIP_TURN",

  INVALID_STATE = "INVALID_STATE",
  MISSING_STATUS = "MISSING_STATUS",
  MISSING_ATTACK_SLOT = "MISSING_ATTACK_SLOT"
}